apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: arunkumar885/frontend:test-v1.0.18
          ports:
            - containerPort: 80
          imagePullPolicy: Always
