apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: arunkumar885/backend:backend-prod-v1.0.44
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
